name: su_bill_manager
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  flutter_hooks: ^0.16.0
  get_storage: ^2.0.2
  gsheets: ^0.3.0
  hive_flutter: ^1.0.0
  local_auth: ^1.1.5
  universal_platform : ^1.0.0-nullsafety 
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
