name: FlutterCI

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "README.md"
      - "docs/**"
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  build-android:
    name: Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup flutter
        uses: subosito/flutter-action@master
        with:
          channel: beta

      - name: Generate android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.4
        with:
          fileName: key.jks
          encodedString: ${{ secrets.KEY_JKS }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Build Flutter app
        run: flutter build apk --split-per-abi

      - name: Upload apk to a release
        uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/apk/release/subillmanager-*
          file_glob: true
          tag: ${{ github.ref }}${{ github.event_name == 'release' && '' || '-nightly' }}
          body: ${{ github.event_name == 'release' && '' || 'Always up to date' }}
          overwrite: true

  build-linux:
    name: Linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@master
        with:
          channel: beta

      - name: Install linux app dependencies
        run: sudo apt-get update -y && sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Enable desktop support
        run: flutter config --enable-linux-desktop

      - name: Build Flutter app
        run: flutter build linux

      - name: Build AppImage
        run: ./create_appimage.sh

      - run: |
          sudo rm -rf ./AppDir/usr/
          sudo rm -rf ./AppDir/AppRun
          sudo rm -rf ./AppDir/.DirIcon

      - name: Compress AppDir
        run: tar czf subillmanager-x86_64.tar.gz -C AppDir/ .

      - name: App tar sha256 sum
        run: sha256sum subillmanager-x86_64.tar.gz

      - uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./subillmanager-x86_64*
          file_glob: true
          tag: ${{ github.ref }}${{ github.event_name == 'release' && '' || '-nightly' }}
          body: ${{ github.event_name == 'release' && '' || 'Always up to date' }}
          overwrite: true

  build_windows:
    name: Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@master
        with:
          channel: beta

      - name: Enable desktop support
        run: flutter config --enable-windows-desktop

      - name: Build Flutter app
        run: flutter build windows

      - uses: papeloto/action-zip@v1
        with:
          files: build/windows/runner/release/
          dest: subillmanager-windows.zip

      - uses: svenstaro/upload-release-action@master
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: subillmanager-windows.zip
          tag: ${{ github.ref }}${{ github.event_name == 'release' && '' || '-nightly' }}
          body: ${{ github.event_name == 'release' && '' || 'Always up to date' }}
          overwrite: true
