name: FlutterCI

on:
  push:
    branches:
      - main
      - dev
    paths-ignore:
      - "README.md"
      - "docs/**"
  workflow_dispatch:
  release:
    types: created

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup flutter
        uses: subosito/flutter-action@master
        with:
          channel: beta

      - name: Generate android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.4
        with:
          fileName: key.jks
          encodedString: ${{ secrets.KEY_JKS }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Build Flutter app
        run: flutter build apk

      - name: Upload apk to a release
        uses: svenstaro/upload-release-action@master
        if: github.event_name != 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/apk/release/app*
          tag: ${{ github.ref }}-nightly
          body: Always up to date
          overwrite: true
          file_glob: true

      - name: Upload apk to a release
        uses: svenstaro/upload-release-action@master
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/apk/release/app*
          tag: ${{ github.ref }}
          body: Always up to date
          overwrite: true
          file_glob: true

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup flutter
        uses: subosito/flutter-action@master
        with:
          channel: beta

      - name: Install linux app dependencies
        run: sudo apt-get update -y && sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Enable desktop support
        run: flutter config --enable-linux-desktop

      - name: Build Flutter app
        run: flutter build linux

      - name: Build AppImage
        run: ./create_appimage.sh

      - name: Upload AppImage to release
        uses: svenstaro/upload-release-action@master
        if: github.event_name != 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: subillmanager-x86_64.AppImage
          tag: ${{ github.ref }}-nightly
          body: Always up to date
          overwrite: true

      - if: github.event_name == 'release'
        run: |
          sudo rm -rf ./AppDir/usr/
          sudo rm -rf ./AppDir/AppRun
          sudo rm -rf ./AppDir/.DirIcon

      - name: Compress AppDir
        if: github.event_name == 'release'
        uses: master-atul/tar-action@master
        id: compress
        with:
          command: c
          files: ./AppDir/*
          outPath: subillmanager-x86_64.tar.gz

      - uses: svenstaro/upload-release-action@master
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./subillmanager-x86_64*
          file_glob: true
          tag: ${{github.ref}}
          body: Always up to date
          overwrite: true
