name: FlutterAppImageCI

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@master
        with:
          channel: dev
          
      - name: Get Packages
        run: flutter pub get
        
      - name: Build App
        run: flutter build linux

      - name: Download AppRun
        run: wget https://github.com/AppImage/AppImageKit SUbillManager.AppDir/AppRun/

      - name: Download required resources to Generate AppImage
        run: wget https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage

      - name: Generate AppImage
        run: ARCH=x86_64 ./appimagetool-x86_64.AppImage SUbillManager.AppDir/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Upload Apk to Release
        id: upload-release-assets
        uses: dwenegar/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          assets_path: *.AppImage

#      - name: Upload to Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: apk-release
#          path: build/app/outputs/apk/release/*-release.apk

