name: FlutterApkCI

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@master
        with:
          channel: dev

      - name: Download Android keystore
        id: android_keystore
        uses: timheuer/base64-to-file@v1.0.4
        with:
          fileName: key.jks
          encodedString: ${{ secrets.KEY_JKS }}

      - name: Create key.properties
        run: |
          echo "storeFile=${{ steps.android_keystore.outputs.filePath }}" > android/key.properties
          echo "storePassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties

      - name: Get Packages
        run: flutter pub get

      - name: Build App
        run: flutter build apk --split-per-abi

      - name: Upload file to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/apk/release/app*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
